In [1]:
import numpy as np								# 导入库时可以使用as来为为库起别名

# np.zeros(shape, dtype=float, order='C')：创建一个形状为shape的全零数组。dtype为数据类型。order=C代表与c语言类似，行优先;order=F代表列优先
print(np.zeros([2,2]))							# 创建一个2*2的全0数组
# np.ones(shape, dtype=None, order='C')：创建一个全1数组，和np.zeros()类似。
print(np.ones([2,2]))								# 创建一个2*2的全1数组
# np.eye(N, M=None, k=0, dtype=float, order='C')：生成一个对角矩阵，N为行数；M为列数，默认和N一样；k为对角线的索引，0代表主对角线。
print(np.eye(2))									# 创建一个2X2的对角矩阵

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]


In [2]:
# numpy.empty(shape, dtype=float, order='C')：生成一个未初始化的数组。
print(np.empty([3,3]))							# 生成一个未初始化的3*3数组
# numpy.full(shape, fill_value, dtype=None, order='C')：生成一个fill_value填充的数组。
print(np.full([3,3],6))							# 生成一个值全为6的3*3数组
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)：生成一个等间隔的数组，start起始值，stop终止值，num数量，endpoint=True表示stop为最后一个值。
print(np.linspace(0,100,10))					# 生成一个等间隔的数组

[[-5.68436073e+185 -1.22900482e-034 -8.31214965e+190]
 [-1.71426939e-141 -4.09325827e+174 -5.27133974e-021]
 [-6.09344526e-025  8.82069792e+199  5.86679289e+276]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [3]:
# numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)：生成一个数组。
a = np.array([1, 2, 3])  					# 创建一维数组
print(a.shape)            					# (3,)，shape为数组形状
print(a.size)								# 3：size为数组元素数量
a[0] = 5                 					# 改变元素取值
print(a[0], a[1], a[2])   					# 5 2 3，根据下标打印数组元素
b = np.array([[1,2,3],[4,5,6]])   		# 创建二维数组
print(b[0, 0], b[0, 1], b[1, 0])   		# 1 2 4，高维数组下标打印数组元素

(3,)
3
5 2 3
1 2 4


In [4]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)							# float64，dtyp查看数组内元素的数据类型
print(arr2.dtype)							# int32

float64
int32


In [5]:
arr = np.arange(10)
arr_slice = arr[5:8]		# 切片方式取值，类似于列表的切片
arr_slice[1] = 999
print(arr)
arr_slice[:]=14		
print(arr)
names = np.array(['Bob','Will','Bob','Joe'])
data = np.array([[-3,2,0,-1],[1,2,3,-4],
                 [2.5,1.7,-0.2,1],[-8,-4,9,10]])
print(data[names=='Bob'])		#根据True False选择数组内的数据
print(data[names=='Bob',2:])

[  0   1   2   3   4   5 999   7   8   9]
[ 0  1  2  3  4 14 14 14  8  9]
[[-3.   2.   0.  -1. ]
 [ 2.5  1.7 -0.2  1. ]]
[[ 0.  -1. ]
 [-0.2  1. ]]


In [6]:
arr3 = np.arange(20).reshape((4,5))	# reshape()方法改变数组形状
print("arr3:",arr3)
print("arr的平均值",arr3.mean())		# mean()方法求平均值 
print("arr的和",arr3.sum())			# sum()求和

print("arr每行的平均值",arr3.mean(1))	#  对每行求平均值，1行，0表示列
print("arr每列的和",arr3.sum(0))		# [30 34 38 42 46]  对每列求和

arr3: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
arr的平均值 9.5
arr的和 190
arr每行的平均值 [ 2.  7. 12. 17.]
arr每列的和 [30 34 38 42 46]


In [1]:
# numpy.random.normal（loc = 0.0，scale = 1.0，size = None ）：从正态分布中抽取随机样本生成一个数组。loc为分布的平均值，scale为标注差，size为数组形状。
samples = np.random.normal(size=(2,2))	#生成一个2*2的随机数组
print(samples)
print("转置后的数组：",samples.T)			# numpy.ndarray.T：数组转置

NameError: name 'np' is not defined